### ISSUE TITLE
Add images

### ISSUE THREAD

**Issue by GuillaumeBAECHLER** [poudre-aux-yeux/rapiquette#1]
Ajouter un champ lien vers une image pour stadium, player, tennis referee

**Comment by tsauvajon** [comment]
Ajouter également des infos sur les joueurs : age, poids (kg), classement ATP, Titres, taille (cm)

**Comment by tsauvajon** [comment]
images ajoutées avec https://github.com/poudre-aux-yeux/rapiquette/commit/059989230390f7491898424ab0ada98d735e2fa5
