### ISSUE TITLE
Ajout mutations

### ISSUE THREAD

**Issue by GuillaumeBAECHLER** [poudre-aux-yeux/rapiquette#2]
Ajouter les mutations pour pouvoir modifier les infos : 
 - joueur
 - arbitres
 - matchs

**Comment by tsauvajon** [comment]
Comment ça fonctionnerait ?
Tu fournis toutes les infos et on stocke ça tel quel, ou tu fournis seulement une partie des infos (ex poids, taille) et on modifie QUE ces infos ?

Pour match tu peux changer l'arbitre, les joueurs, le stade dans tous les cas ?
Pour le stade je vois pas d'inconvénient, pour les joueurs si (surtout si le match a démarré)

**Comment by tsauvajon** [comment]
Solution retenue:
je reçois un objet ENTIER, je le stocke tel quel (PUT et pas PATCH).
Pour la modification de match, on peut modifier l'arbitre (changement de dernière minute), on peut modifier le cours (cas de force majeure par exemple), on peut modifier un joueur (http://www.sport-u-lille.com/cmsms_new/uploads/REGLEMENT%20TENNIS%20PAR%20%20EQUIPE.pdf)

**Comment by tsauvajon** [comment]
Code implémenté avec https://github.com/poudre-aux-yeux/rapiquette/commit/473f7d0dbb9c684458705d8e59b9c7aa768a199c
