### ISSUE TITLE
Changer CreatePlayerInput

### ISSUE THREAD

**Issue by GuillaumeBAECHLER** [poudre-aux-yeux/rapiquette#3]
Il faudrait ajouter les nouveaux attributs du player au CreatePlayerInput pour que je puisse en ajouter. Pour rappel :
- image
- weight
- ranking
- titles
- height

**Comment by tsauvajon** [comment]
Qu'est-ce qui doit être obligatoire / qu'est-ce qui être facultatif ?

**Comment by tsauvajon** [comment]
J'ai tout ajouté, avec tous les paramètres obligatoires (+ nationalité, cf https://github.com/poudre-aux-yeux/rapiquette/issues/4).

Si c'est OK pour tous les params obligatoires tu peux close ? Sinon bah on change.

@GuillaumeBAECHLER

**Comment by GuillaumeBAECHLER** [comment]
Facultatifs :
- weight
- height
- ranking
Le reste obligatoire 😄
